### PR TITLE
updates dependencies

### PR DESCRIPTION
**Pull request by dtillner**
Updates dependencies as requested in #12.

- changes from yarn to npm. Could not find a actual docker image with yarn (now using node:18-alpine).
- fixes tests as async and done() is not supported in jest

### CODE REVIEW

**Comment by dtillner** [comment]
Would be nice if someone could check this pull request and give feedback or merge it. **:wave:**

@Jonahss 
@spencerwilson
@cmidgley
@smulikHakipod

Thank you very much. :smile:

**Review by matziol — APPROVED** [review]

**Comment by avaly** [comment]
It would be very helpful to get these changes merged and published on npm. Thanks!

**Comment by Jonahss** [comment]
@antontsvil ^

I no longer have access to this repository

**Review by antontsvil — APPROVED** [review]

**Comment by antontsvil** [comment]
released with version 3.2.0

**Pull request merged**
