### PR TITLE
Rewrite with TypeScript and simplify

### PR DESCRIPTION
**Pull request by dchenk**

### CODE REVIEW

**Comment by Jonahss** [comment]
Hey thanks!

I noticed that the `index.ts` is much simpler, doing less. Are the original behaviors around registering listeners prior to connecting, and ignoring the multiple 'connected' events, handled in the updated code?

@antontsvil what do you think? Will this work in the origin codebase?

**Comment by dchenk** [comment]
@Jonahss I didn't expect such a quick reply. I'm actually trying to be extremely practical at the moment to get this library do what I need for a current project, and I wasn't sure that changing the functionality around registering listeners and other things would be acceptable for this library. It's something I'd consider coming back to and adding later.

In fact I opened this PR by accident — I thought I was targeting my fork. 

I'd be happy to come back when I have more time and consolidate the efforts sometime in the near future though.

**Comment by Jonahss** [comment]
Oh ok! Best of luck, glad you at least found this repo helpful.

**Comment by antontsvil** [comment]
@Jonahss I'm glad I waited until the weekend before testing this :laughing:

**Pull request closed without merging**
