### PR TITLE
asyncIterator promise

### PR DESCRIPTION
**Pull request by smulikHakipod**
Hey,
I want to use Postgres pubsub to push notifications for each user in my app. I have each channel for a user in the app. The problem, is that I don't know which users I have in time of creation of the pub-sub, so I cannot really pass it as parameter. I suggest a workaround - add asyncIteratorPromised function. What do you think? Thanks

### CODE REVIEW

**Comment by Jonahss** [comment]
Nice. I'm fine with adding this, will be useful to people, thanks!

I think for your use case, it might be better to have a single channel for the kind of message you are sending, and then use the filters to send messages to the users logged in, that's what I did in my application.

So for example, if I have a config object for every user, and I want all connected users to subscribe to changes to their config, I do it this way:
```
export const Subscription = new GraphQLObjectType({
  name: 'Subscription',
  fields: (): any => ({
    userConfig: {
      type: UserConfigType,
      subscribe: withFilter(
          () => pubsub.asyncIterator(PubSubTopic.USER_CONFIG_CHANGE),
          (payload: ConfigChangeMessage, _variables, context: WebSocketContext) => {
            return payload.userId === context.state.myId;
          },
      ),
      resolve: async (payload: ConfigChangeMessage, _args, context) => {
        const updatedConfig = await getUserConfig({ id: payload.UserId, ctx: context });
        return updatedConfig;
      },
    }
})
```

So the `withFilter` call and returning `payload.userId === context.state.myId`, that way, any users currently subscribed get the changes to themselves and all other users subscribed don't get anything.

Notice I'm also not putting the whole updated object into the pubsub queue, but only a message that the object changed. Then the server gets the object from the database itself. This way, we don't accidentally run into the 10,000 character message limit in postgres.

But if you need to use separate channels for each user, this is a fine addition.
What do you think?

**Comment by smulikHakipod** [comment]
Hi, thanks for the help!
I am thinking your approach is similar to the one from NestJS docs:

image

The issue I had with this approach in my case is that this filter have to be called the amount of users * messages.
For example, if I have 10K users sending 10K messages, the `payload.userId === context.state.myId` will have to be called 100M times. When growing this becomes much worse. Am I wrong?
Though I am not sure what is the overhead of a channel, it might be worse. 

Regarding your idea with the ID, sure, I think that as well, only save the ID and not the whole message, but it does not solve the issue I described above and would still probably need different channels for different users.

**Comment by Jonahss** [comment]
Ah yup, my solution was basically copied from the example code.
Yes, the downside of this solution is that at very high numbers of users, you'll run into scaling problems.
Sounds like you understand your problem!

**Review by Jonahss — APPROVED** [review]

**Comment by Jonahss** [comment]
published as version 3.1.0

**Pull request merged**
